### ISSUE TITLE
Shorter URL / Filename

### ISSUE THREAD

**Issue by crunchprank** [ziggi/zimg-host#16]
What and where about in the PHP script would I change if I'd like to shorten the generated filename? After digging around a bit, it looks like it's using the MD5 of the image file to generate the name? I'd like to be able to shorten it to the length of imgur's (e.g. imgur.com/s9K5x.png). Thanks for your help!

**Comment by ziggi** [comment]
You can try make this changes (I have not test it, but it should work):

https://github.com/ziggi/zimg-host/blob/master/upload.class.php#L71
```php
$new_name = hash('crc32b', microtime() . $urls_array[$i] . rand(0, 9999)) . '.' . $this->_allowed_types[ $array_result[$i]['type'] ]['file_format'];
```

https://github.com/ziggi/zimg-host/blob/master/upload.class.php#L142
```php
$new_name = hash('crc32b', microtime() . $files[$i]['name'] . $files[$i]['tmp_name'] . rand(0, 9999))  . '.' . $this->_allowed_types[$type]['file_format'];
```

I will make those changes later.

**Comment by crunchprank** [comment]
Tested and working. Thanks!
