### ISSUE TITLE
Not Showing correct links

### ISSUE THREAD

**Issue by duramato** [ziggi/zimg-host#24]
Its showing up like this after uploading a file
![image](https://cloud.githubusercontent.com/assets/10121067/13162127/95f269e2-d69a-11e5-80eb-99046408f73b.png)

But if i navigate on the /file dir , they are there like `/file/Q/k/QkTUIJRF.gif` for example

**Comment by ziggi** [comment]
You need to give read privileges to your http server.

**Comment by duramato** [comment]
It has the correct previlages, it creates the folders just fine but for some reason its showing them icorrectly on the page "ui"

**Comment by ziggi** [comment]
Are you using nginx or Apache? Are rewrite_module is enabled?

**Comment by duramato** [comment]
Apache , i dont know if rewritte_module  is enabled is there any easy way to check if it is?

**Comment by ziggi** [comment]
Open your Apache configuration file (I don't know where this file on your OS, but for me this file located here: `/etc/httpd/conf/httpd.conf`) and try to find this line:
```
LoadModule rewrite_module modules/mod_rewrite.so
```

**Comment by duramato** [comment]
I do not have that file and i cant find any LoadModule on apache2.conf

**Comment by ziggi** [comment]
Try to use this command:
```
sudo a2enmod rewrite
```
The command activates the rewrite module.

**Comment by duramato** [comment]
yup, i have it after all :P 
`
a2enmod rewrite
Module rewrite already enabled
`

**Comment by ziggi** [comment]
Run:
```
service apache2 restart
```
and check links now

**Comment by duramato** [comment]
Same thing continues to happen, also ive noted that upload from file doesnt even show the "placeholder" for the image like on the OP screen

**Comment by ziggi** [comment]
Maybe you got some errors in console? (Ctrl + Shift + J in Chrome)

**Comment by duramato** [comment]
```
scripts.js:117 POST http://zimg.domain.com/api/upload.php 500 (Internal Server Error)
upload @ scripts.js:117
window.uploadFiles @ scripts.js:97(anonymous function) @ scripts.js:11
VM293:1 
Uncaught SyntaxError: Unexpected end of input
addImagesFromArray @ scripts.js:24
request.onload @ scripts.js:106
```

**Comment by ziggi** [comment]
And what is written at this time in `/var/log/apache2/error.log`?

**Comment by duramato** [comment]
mm now the js error are gone and the box shows when i upload a file, wierd. But the main issue its still existant
Nothing in the logs

**Comment by ziggi** [comment]
I think problem in PHP settings or something like that, closed.

**Comment by zikwal** [comment]
Та же проблема - просто скопировал и вставил на под домен!

**Comment by iamjacksgithub** [comment]
This appears to happen when the project is set up under a subfolder and not at the root of the webserver.
