### ISSUE TITLE
BB Code

### ISSUE THREAD

**Issue by bolach** [ziggi/zimg-host#27]
Hi there,
How can we change the direct image link to BB code embed code?
The code is simple, is just [img]www.image.com/1.jpg[/img]
I think it would be easy to change on php, but i don't know how.

**Comment by ziggi** [comment]
You need to change this string: https://github.com/ziggi/zimg-host/blob/master/tpl/material/file_item.php#L10
to this:
```php
<input class="mdl-textfield__input" type="text" onclick="select()" readonly value="[img]<?=$url?>[/img]" />
```

**Comment by bolach** [comment]
Thank you!
