### ISSUE TITLE
question - changing upload folder location

### ISSUE THREAD

**Issue by georgesuba** [ziggi/zimg-host#35]
Hi Ziggi,
Thank you for great script. Can you point me where I can change upload folder? basically I would like to have uload form in /a/zimg/ and images links in /a/file.png - is that even possible? Thank you.

**Comment by ziggi** [comment]
https://github.com/ziggi/zimg-host/blob/0e2f7199b444397f6fb60fddbdecf215225ef531/include/upload.class.php#L44-L46
https://github.com/ziggi/zimg-host/blob/0e2f7199b444397f6fb60fddbdecf215225ef531/bootstrap.php#L39-L43

Make sure that the new directory is writable by the web server

**Comment by georgesuba** [comment]
Brilliant, THANK YOU!
